version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

  gpt4free:
      image: hlohaus789/g4f:latest
      shm_size: 2gb
      ports:
        - '8080:8080'
        - '1337:1337'
        - '7900:7900'
    
